@startuml mastermind
Mastermind *-down-> Board
Mastermind *-down-> "2" Player
Mastermind *-down-> Turn

Board o-down-> "0..12" CheckCode

Board o-down-> "0..12" ControlLine
Board o-down-> SecretCode
Board o-down-> "2" ScoreLine

ScoreLine o-down-> Score


PlayerCheckerCode o---> CheckCode
PlayerMakerCode o---> SecretCode
PlayerMakerCode o---> ControlLine
Player o---> Score

Player --> Board
Player o---> Goal
together {
Player <|-- PlayerMakerCode
Player <|-- PlayerCheckerCode
}
Action <|-down- SecretCodeAction
Action <|-down- CheckCodeAction
Action <|-down- ControlCodeAction
Action <|-down- ScoreAction
Action <|-down- WinAction
Turn ---> "2" Player


Code *---> "5" Color
Code <|-down- SecretCode
Code <|-down- CheckCode
Code --> Position

ControlLine *-down-> "0..5" SpikeControl
Score *-down-> SpikeScore

Color <|--- Red
Color <|--- Blue
Color <|--- Green
Color <|--- Yellow
Color <|--- Pink
Color <|--- White
Color <|--- Black
Color <|--- Brown

SpikeControl <|-down- SpikeFullOk
SpikeControl <|-down- SpikeColorOk
SpikeScore <|-down- SpikeRed
SpikeScore <|-down- SpikeBlue

Goal ..> WinAction
Goal ..> CheckCodeAction

Action ..> Color
Action ..> SpikeScore
Action ..> SpikeControl
Action ..> Board : target
@enduml